---
name: Cloudflared Caddy
version: 7.0.0-caddy.0
breaking_versions:
  - 5.3.7
  - 6.0.0
slug: cloudflared
description: "Use a Cloudflare Tunnel to remotely
  connect to Home Assistant without opening any ports"
url: "https://github.com/felipecrs/cloudflared-caddy-hass-addon/"
startup: services
init: false
hassio_api: true
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - homeassistant_config
options:
  external_hostname: ""
  additional_hosts: []
ports:
  36500/tcp: null
  80/tcp: null
  443/tcp: null
  443/udp: null
privileged:
  # https://hub.docker.com/_/caddy#linux-capabilities:~:text=caddy_container_id%20caddy%20reload-,Linux%20capabilities,-Caddy%20ships%20with
  - NET_ADMIN
schema:
  external_hostname: str?
  additional_hosts:
    - hostname: str
      service: str
      disableChunkedEncoding: bool?
      internalOnly: bool?
  tunnel_name: str?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  use_builtin_proxy: bool?
  tunnel_token: str?
  post_quantum: bool?
  run_parameters:
    - match(^(--edge-bind-address|--edge-ip-version|--grace-period|--ha-connections|--logfile|--loglevel|--pidfile|--protocol|--region|--retries|--tag)=.*$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
